
---
- name: Create AWS EC2 Instance
  hosts: local
  connection: local
  gather_facts: false
  vars:
          keypair       : maksym
          instance_type : t2.micro
          image         : ami-0818dadaae552a40b
          region        : eu-central-1
          count         : 1
          security_group: Ansible-SecurityGroup
          aws_access_key: AKIAJVRU2TPNDGHUPQWA
          aws_secret_key: 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
  tasks:
          - name: Create group with Port 22, 80 and 443 Open to 0.0.0.0/0
            ec2_group:
                   name       : "{{ security_group }}"
                   description: Security Group for Server with port 22, 80, 443 Open
                   region     : "{{ region }}"
                   rules:
                           - proto    : tcp
                             from_port: 22
                             to_port  : 22
                             cidr_ip  : 18.198.41.162/32
                           - proto    : tcp
                             from_port: 22
                             to_port  : 22
                             cidr_ip  : 3.121.126.213/32
                           - proto    : tcp
                             from_port: 22
                             to_port  : 22
                             cidr_ip  : 18.192.93.16/32
                           - proto    : tcp
                             from_port: 80
                             to_port  : 80
                             cidr_ip  : 0.0.0.0/0
                           - proto    : tcp
                             from_port: 443
                             to_port  : 443
                             cidr_ip  : 0.0.0.0/0
                           - proto    : icmp
                             from_port: -1
                             to_port  : -1
                             cidr_ip  : 18.198.41.162/32
                           - proto    : icmp
                             from_port: -1
                             to_port  : -1
                             cidr_ip  : 3.121.126.213/32
                           - proto    : icmp
                             from_port: -1
                             to_port  : -1
                             cidr_ip  : 18.192.93.16/32
                   rules_egress:
                           - proto    : all
                             cidr_ip  : 0.0.0.0/0
                   aws_access_key: "{{ aws_access_key }}"
                   aws_secret_key: "{{ aws_secret_key }}"

          - name: Create New AWS EC2 Server
            ec2:
                    key_name      : "{{ keypair }}"
                    instance_type : "{{ instance_type }}"
                    image         : "{{ image }}"
                    group         : "{{ security_group }}"
                    region        : "{{ region }}"
                    instance_tags :
                            Name: Prod
                            Type: AnsibleEC2
                    count         : "{{ count }}"
                    wait          : true
                    aws_access_key: "{{ aws_access_key }}"
                    aws_secret_key: "{{ aws_secret_key }}"
            register: ec2

          - name: Allocating elastic IP to instance
            ec2_eip:
                    aws_access_key           : "{{ aws_access_key }}"
                    aws_secret_key           : "{{ aws_secret_key }}"
                    in_vpc                   : yes
                    reuse_existing_ip_allowed: yes
                    state                    : present
                    region                   : "{{ region }}"
                    device_id                : "{{ ec2.instance_ids[0] }}"
                    ip                       : 18.193.63.106
            register: instance_eip
          - debug: var=instance_eip.public_ip

          - name : Print all ec2 variables
            debug: var=ec2



