name: 'action'
#on: pull_request
on:
  workflow_call:
    inputs: 
      acr_image_tag:
        required: false
        type: string
    outputs:
      exit_code:
        value: ${{ jobs.branch-naming-rules.outputs.output }}
      
  workflow_dispatch:
    inputs: 
      image_tag:

    
  

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step.outputs.exit_code }}
    steps:
      - name: setup varible
        if: "${{ github.event.inputs.image_tag == '' &&  github.event.inputs.acr_image_tag != ''}}"
        run: echo "image=${{ inputs.acr_image_tag }}" >> $GITHUB_ENV
      - name: setup custom varible
        if: "${{ github.event.inputs.image_tag != '' }}"
        run: echo "image=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
      - name: setup secret
        if: "${{ github.event.inputs.acr_image_tag == '' }}"
        run: echo "image=${{ secrets.CURRENT_IMAGE_VERSION }}" >> $GITHUB_ENV
      - name: test
        run: |
          echo ${{ env.image }}
      - id: step
        run: echo ::set-output name=exit_code::1
      
