name: 'action'
#on: pull_request
on:
  workflow_call:
  workflow_dispatch:
    inputs: 
      image_tag:

    
  

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: setup varible
        if: "${{ github.event.inputs.image_tag == '' }}"
        run: echo "image=${{ github.run_number }}" >> $GITHUB_ENV
      - name: test
        run: |
          echo ${{ env.image }}
      
