name: 'action'
#on: pull_request
on:
  workflow_call:
  workflow_dispatch:
    inputs: 
      image_tag:

    
  

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: setup varible
        if: "${{ github.event.inputs.image_tag == '' }}"
        env:
          image: ${{ github.run_number }}
      - name: test
        run: |
          echo ${{ env.image }}
      
