name: 'action'
#on: pull_request
on: 
  workflow_call:
    inputs:
      run_number:
        required: true
        type: string
  workflow_dispatch:

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ run_number }}
      
