name: 'action'
#on: pull_request
on:
  workflow_call:
  workflow_dispatch:
    inputs: 
      image_tag:

    
  

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.event.inputs.image_tag }}
      
