name: 'action'
#on: pull_request
on: 
  workflow_dispatch:

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.run_number }}
      
