name: Call reusable 2

on: 
 workflow_call:
    inputs: 
      name:
        required: true
        type: string

jobs:
 pre-build:
  runs-on: ubuntu-latest
  outputs:
      service-projects: ${{ steps.configuration.outputs.services }}
    
  steps:
    - name: Clone BE repository
      uses: actions/checkout@v3
    
    - name: Read Configuration
      id: configuration
      uses: CumulusDS/get-yaml-paths-action@v1.0.1
      with:
        file: sln.build.yml
        service-projects: '"services"'
        
    - name: test
      run: echo ${{ steps.configuration.outputs.service-projects }}
 call_reuable2:
   needs: pre-build
   strategy:
      fail-fast: false
      matrix: 
        source_dir: ${{ fromJson(needs.pre-build.outputs.service-projects) }}
   uses: Maksym-Popovkin/Project/.github/workflows/reusable.yaml@master
   with:
     source: ${{ matrix.source_dir }}
