name: Call reusable 1

on:
  push:
    branches:
      - Check

jobs:
  parse_sln-build-config_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository
      uses: actions/checkout@v3
      with:
        path: .
        ref: Check
        
    - name: Prepare artifact
      run: |
        echo "image1" > test.txt
        echo "image2" >> test.txt
        mkdir test
        mkdir test/test2
        echo "image3" > test/test.txt
        echo "image4" > test/test2/test.txt
        
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
          test.txt
          test2.txt
          
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact2
        path: |
          test/
          
  call_reuable:
    needs: parse_sln-build-config_file
    uses: Maksym-Popovkin/Project/.github/workflows/call_second_reusable.yaml@Check
