name: Call reusable 2

on: 
 workflow_call:

jobs:
  prepare_artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: |
        ls -la
        cat test.txt
        echo "-----------"
        cat test2.txt
            
  call_reuable2:
   needs: prepare_artifacts
   uses: Maksym-Popovkin/Project/.github/workflows/reusable.yaml@Check
