name: Call reusable 1

on: [workflow_dispatch]

jobs:
  parse_sln-build-config_file:
    runs-on: ubuntu-latest
#     outputs:
#       dotnet-version: ${{ steps.configuration.outputs.dotnet-version }}
#       service-projects: ${{ steps.configuration.outputs.service-projects }}
    steps:
    # Clone code from BE repository
    - name: Clone BE repository
      uses: actions/checkout@v3
      with:
        path: .
    
    - name: Read Configuration
      id: configuration
      uses: CumulusDS/get-yaml-paths-action@v1.0.1
      with:
        file: sln.build.yml
        dotnet-version: '"dotnet-version"'
        service-projects: '"service-projects"'
        unit-test-project: '"unit-test-project"'
        
    - name: test
      run: echo ${{ steps.configuration.outputs.service-projects }}
#   call_reuable1:
#     needs: parse_sln-build-config_file
#     uses: Maksym-Popovkin/Project/.github/workflows/call_second_reusable.yaml@master
#     with:
#       name: ${{ needs.parse_sln-build-config_file.outputs.service-projects }}
