name: Call reusable 2

on: 
 workflow_call:
    inputs: 
      name:
        required: true
        type: string

jobs:
 pre-build:
  runs-on: ubuntu-latest
  outputs:
      service-projects: ${{ steps.configuration.outputs.service-projects }}
    
  steps:
    - name: Clone BE repository
      uses: actions/checkout@v3
    
#     - name: Read Configuration
#       id: configuration
#       uses: CumulusDS/get-yaml-paths-action@v1.0.1
#       with:
#         file: sln.build.yml
#         service-projects: '"services"[]'
               
    - name: test
      id: configuration
      run: |
        #service=$(echo [\"src/Services.TimeClock\",\"src/Services.TimeClock\",\"src/Service.Chat\",\"src/Service.Chat\"])
        #service=$(echo {\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]})
        #service=$(echo [\"name\":\"feature-toggle-cache-service\",\"project\":\"FeatureToggle.Cache.Service/FeatureToggle.Cache.Service.csproj\",\"helm-chart\":\"charts/feature-toggle-cache-service\",\"unit-tests\":[\"FeatureToggle.UnitTests/FeatureToggle.UnitTests.csproj\"]])
        #echo $service
        #echo "service-projects={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        echo "service-projects={\"include\":[{\"name\":\"feature-toggle-cache-service\",\"project\":\"FeatureToggle.Cache.Service/FeatureToggle.Cache.Service.csproj\",\"helm-chart\":\"FeatureToggle.UnitTests/FeatureToggle.UnitTests.csproj;FeatureToggle.UnitTests/FeatureTog\"}]}" >> $GITHUB_OUTPUT
      
    - name: test2
      run: echo ${{ steps.configuration.outputs.service-projects }}
 call_reuable2:
   needs: pre-build
   strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.pre-build.outputs.service-projects) }}
   uses: Maksym-Popovkin/Project/.github/workflows/reusable.yaml@master
   with:
     source: ${{ matrix.name }}
     source1: ${{ matrix.project }}
     source2: ${{ matrix.helm-chart }}
     
