name: Reusable

on: 
 workflow_call:

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: |
        ls -la
        cat test.txt
        echo "-----------"
        cat test2.txt
