name: Reusable

on: 
 workflow_call:
    inputs: 
      name:
        required: true
        type: string

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - name: Get changed files
      run: |
        echo "test"
        echo ${{ inputs.name }}
