name: Reusable

on: 
 workflow_call:
    inputs: 
      source:
        required: true
        type: string
      source1:
        required: true
        type: string
      source2:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - name: Get changed files
      run: |
        echo ${{ inputs.source }}
        echo ${{ inputs.source1 }}
        echo ${{ inputs.source2 }}
        echo ${{ inputs.dotnet-version }}
