name: Reusable

on:
  push:
    branches:
      - check-test

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact2
    
    - name: Display structure of downloaded files
      run: |
        ls -la
        echo "test.txt file contents:"
        cat test.txt
        echo "test/test.txt file contents:"
        cat test/test.txt
        echo "test/test2/test.txt file contents:"
        cat test/test2/test.txt
