name: Jekyll site CI

on:
  push:
    branches:
      - "master"

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - name: setup default variable
      run: echo "image=${{ github.run_number }}" >> $GITHUB_ENV
  build:
    uses: ./.github/workflows/action.yml
    with:
      acr_image_tag: ${{ env.image }}
