name: Jekyll site CI

on: [workflow_dispatch]

env: 
  REPORT: "Report Demographic - w.o. Roster"
  WORKSPACE: "Features-Presentaion"
  #TABULAR_EDITOR: "TabularEditor.exe"

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: master
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Maksym-Popovkin/git_test
        #token: ${{ secrets.GH_PAT }}
        path: git_test
    - name: Install a SQL Server suite of tools
      uses: potatoqualitee/mssqlsuite@v1.5.1
      with:
        install: sqlengine
    - name: Install Tabular Editor
      run: |
        $TabularEditorUrl = "https://cdn.tabulareditor.com/files/te2/TabularEditor.Portable.zip" 
        $DownloadDestination = join-path (get-location) "TabularEditor.zip"
        Invoke-WebRequest -Uri $TabularEditorUrl -OutFile $DownloadDestination
        Expand-Archive -Path $DownloadDestination -DestinationPath (get-location).Path
        Remove-Item $DownloadDestination
        echo $TABULAR_EDITOR
        $TABULAR_EDITOR = "TabularEditor.exe"
        $p = Start-Process -FilePath $TABULAR_EDITOR
