name: Jekyll site CI

on:
  push:
    branches:
      - "master"
    paths:
      - 'pet/**'
  workflow_dispatch:

env:  
  PACKAGES_FOLDER: Modules

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'pet/.mvn/wrapper/**'
          #frontend:
            #- 'frontend/**'

    # run only if 'backend' files were changed
    - name: Intstall MicrosoftPowerBIMgmt
      shell: pwsh
      run: |
        $tenant_id = ${{ secrets.TEST }}
    - name: backend tests
      if: steps.filter.outputs.src == 'true'
      run: echo "true"
