name: Jekyll site CI

on:
  push:
    branches:
      - "master"

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::${{ github.run_number }}"
  build:
    uses: ./.github/workflows/action.yml
    with:
      acr_image_tag: ${{needs.pre-build.outputs.output1}}
