name: Build and publish nuget artifact

on:
  push:
    branches: master
    paths:
      - 'src/*/*Service.Client/*'

jobs:
  build_and_publish_nuget_artifact:
    runs-on: ubuntu-latest
    steps:
 
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
