name: Jekyll site CI

on:
  push:
    branches:
      - "master"
    paths:
      - 'pet/**'
  workflow_dispatch:

env:  
  PACKAGES_FOLDER: Modules

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      
    - name: Run step when a file changes
      if: github.event.paths == 'pet/.mvn/wrapper/**'
      run: |
        echo "Your my-file.txt file has been modified."
