name: Jekyll site CI

on:
  push:
    branches:
      - "master"
    paths:
      - 'pet/**'
  workflow_dispatch:

env:  
  PACKAGES_FOLDER: Modules

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change text file
      run: |
        echo "Modified" > new.txt

    - name: Change file in directory
      run: |
        echo "Changed" > pet/new.txt

    - name: Get changed files using defaults
      id: changed-files
      uses: tj-actions/changed-files@v27
      
    - name: Run step when a file changes
      if: contains(steps.changed-files.outputs.modified_files, 'pet/**')
      run: |
        echo "Your my-file.txt file has been modified."
