name: Jekyll site CI

on: [workflow_dispatch]
  #push:
   # branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    #- name: Clone code
     # uses: actions/checkout@v3
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: Maksym-Popovkin/diploma
        #token: ${{ secrets.my_pat }}
    - name: Install a SQL Server suite of tools
      uses: potatoqualitee/mssqlsuite@v1.5.1
      with:
        install: sqlengine, sqlclient, sqlpackage
