name: Jekyll site CI

on:
  push:
    branches:
      - "master"

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step.outputs.run_number }}
    steps:
      - id: step
        run: echo "::set-output name=run_number::${{ github.run_number }}"
  build:
    needs: pre-build
    uses: ./.github/workflows/action.yml
    with:
      acr_image_tag: ${{needs.pre-build.outputs.output}}
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: gliech/create-github-secret-action@v1
        with:
          name: Current_image_version
          value: ${{ github.run_number }}
          pa_token: ${{ secrets.PA_TOKEN }}
