name: Build and publish nuget artifact

on:
  push:
    branches: master
    paths:
      - 'src/*/*Service.Client/*'

jobs:
  build_and_publish_nuget_artifact:
    runs-on: ubuntu-latest
    steps:
 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
          
    - name: Get changed files in the docs folder
      id: changed-files
      uses: tj-actions/changed-files@v31
      with:
        files: |
          src/*/*Service.Client
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
