name: Jekyll site CI

on: [workflow_dispatch]

env:  
  PACKAGES_FOLDER: Modules

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: master
    - name: test2
      run: |
        echo ${{ github.run_number }}
        ls
        cd git_test
        ls
    - name: Install a SQL Server suite of tools
      uses: potatoqualitee/mssqlsuite@v1.5.1
      with:
        install: sqlengine, sqlclient, sqlpackage, localdb
    
    - name: Install Tabular Editor
      run: |
        $TabularEditorUrl = "https://cdn.tabulareditor.com/files/te2/TabularEditor.Portable.zip" 
        $DownloadDestination = join-path (get-location) "TabularEditor.zip"
        Invoke-WebRequest -Uri $TabularEditorUrl -OutFile $DownloadDestination
        Expand-Archive -Path $DownloadDestination -DestinationPath (get-location).Path
        Remove-Item $DownloadDestination
    
    - name: Make Install Modules Folder
      run: New-Item "$PSScriptRoot\${env:PACKAGES_FOLDER}" -ItemType Directory -Force

    - name: Install Redgate Tooling
      run: |
        $LocalModules = "$PSScriptRoot\${env:PACKAGES_FOLDER}"
        Get-PackageProvider NuGet -ForceBootstrap | Out-Null
        Import-PackageProvider PowerShellGet 
        Save-Module -Name PowerShellGet -Path $LocalModules -MinimumVersion 1.6 -Force -ErrorAction SilentlyContinue
        Save-Module -Name SqlChangeAutomation -Path $LocalModules -Force -ErrorAction Stop -AcceptLicense        
    
    - name: Test
      run: |
        python --version
        py -m pip install pyodbc
        #Install-Module -Name PowerShellGet -MinimumVersion 2.0.1
        #Install-Module -Name SqlChangeAutomation
        #Import-Module SqlChangeAutomation
    
    - name: Build Redgate Packages      
      run: |
        $LocalModules = "$PSScriptRoot\${env:PACKAGES_FOLDER}"
        $env:PSModulePath = "$LocalModules;$env:PSModulePath"

        Import-Module SqlChangeAutomation
