name: CI

on:
  workflow_dispatch:
    inputs: 
      image_tag:
        description: 'ACR image tag'
        required: true
      selecting_app:
        description: 'Which app need build'
        required: true
        default: 'Both'
        type: choice
        options:
        - Client
        - Admin
        - Both

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    
    # Checks out the repository 
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          adminapp:
            - 'ui/CARWebApp/CARWebApp.Admin/**'
          clientapp:
            - 'ui/CARWebApp/CARWebApp.Client/**'
    
    - name: setup default variable
      if: "${{ github.event.inputs.image_tag == '' }}"
      run: echo "image=v0.0.${{ github.run_number }}" >> $GITHUB_ENV
    - name: setup custom variable
      if: "${{ github.event.inputs.image_tag != '' }}"
      run: echo "image=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
    - name: Build and push Admin image to ACR
      if: (steps.filter.outputs.adminapp == 'true' && github.event.inputs.image_tag == '') || (github.event.inputs.image_tag != '' && github.event.inputs.selecting_app == 'Admin')
      run: echo true
      
