name: Jekyll site CI

on: push

jobs:
   example-job:
      runs-on: ubuntu-latest
      steps:
         - name: Set imagePullSecret
           uses: azure/k8s-create-secret@v2
           with:
              namespace: 'car-webapp'
              secret-name: 'car_web_app_acr_secret'
              container-registry-url: 'sistestacr.azurecr.io'
              container-registry-username: 'sistestacr'
              container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
           id: create-secret
