name: CI

on:
  workflow_dispatch:
    inputs: 
      image_tag:
        required: true
      logLevel:
        description: 'Log level'
        required: true
        type: choice
        options:
        - Client
        - Admin
        - Both

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    
    # Checks out the repository 
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          adminapp:
            - 'ui/CARWebApp/CARWebApp.Admin/**'
          clientapp:
            - 'ui/CARWebApp/CARWebApp.Client/**'
    
    - name: setup default variable
      if: "${{ github.event.inputs.image_tag == '' }}"
      run: echo "image=v0.0.${{ github.run_number }}" >> $GITHUB_ENV
    - name: setup custom variable
      if: "${{ github.event.inputs.image_tag != '' }}"
      run: echo "image=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
      
