name: Build and publish nuget artifact

on:
  push:
    branches: master
    paths:
      - 'src/*/*Service.Client/*'

jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
          
    - name: Get changed files in the docs folder
      id: changed-files
      uses: tj-actions/changed-files@v31
      with:
        files: |
          src/*/*Service.Client
    - name: List all changed files
      run: echo ${{ steps.changed-files.outputs.all_changed_files }}
