name: Jekyll site CI

on:
  push:
    branches:
      - "master"

jobs:
  pre-build:
    env: 
      GITHUB_TOKEN: ${{ secrets.CURRENT_IMAGE_VERSION }}
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step.outputs.run_number }}
      output2: ${{ steps.step2.outputs.token }}
    steps:
      - id: step
        run: echo "::set-output name=run_number::${{ github.run_number }}"
      - id: step2
        run: echo "::set-output name=token::${{ env.GITHUB_TOKEN }}"
  build:
    needs: pre-build
    uses: ./.github/workflows/action.yml
    with:
      acr_image_tag: ${{needs.pre-build.outputs.output1}}
    
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: gliech/create-github-secret-action@v1
        with:
          name: Current_image_version
          value: ${{ github.run_number }}
          pa_token: ${{ secrets.PA_TOKEN }}
  post:
    needs: [test, build, pre-build]
    if: needs.build.outputs.exit_code != 0
    uses: ./.github/workflows/action.yml
    with:
      acr_image_tag: ${{ secrets.CURRENT_IMAGE_VERSION }}
